// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { createRequire } from "module";
const require = createRequire(import.meta.url);
try {
  require("dotenv/config");
} catch {
  // dotenv nicht vorhanden (z. B. in Docker); DATABASE_URL aus Umgebung nutzen
}
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
