"""initial v2 schema

Revision ID: 3dad6d21c1b8
Revises: 
Create Date: 2026-03-22 16:14:36.243255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dad6d21c1b8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cubes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tournaments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('SETUP', 'VOTING', 'DRAFTING', 'FINISHED', name='tournamentstatus'), nullable=False),
    sa.Column('join_code', sa.String(length=8), nullable=False),
    sa.Column('max_rounds', sa.Integer(), nullable=False),
    sa.Column('is_test', sa.Boolean(), nullable=False, server_default='false'),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tournaments_join_code'), 'tournaments', ['join_code'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('drafts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('round_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'FINISHED', name='draftstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'round_number', name='uq_tournament_round')
    )
    op.create_table('tournament_cubes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('cube_id', sa.Uuid(), nullable=False),
    sa.Column('max_players', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cube_id'], ['cubes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'cube_id', name='uq_tournament_cube')
    )
    op.create_table('tournament_players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('match_points', sa.Integer(), nullable=False),
    sa.Column('game_wins', sa.Integer(), nullable=False),
    sa.Column('game_losses', sa.Integer(), nullable=False),
    sa.Column('dropped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_id'], ['tournaments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_id', 'user_id', name='uq_tournament_user')
    )
    op.create_table('cube_votes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tournament_player_id', sa.Uuid(), nullable=False),
    sa.Column('tournament_cube_id', sa.Uuid(), nullable=False),
    sa.Column('vote', sa.Enum('DESIRED', 'NEUTRAL', 'AVOID', name='votetype'), nullable=False),
    sa.ForeignKeyConstraint(['tournament_cube_id'], ['tournament_cubes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_player_id'], ['tournament_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tournament_player_id', 'tournament_cube_id', name='uq_player_cube_vote')
    )
    op.create_table('draft_photos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('tournament_player_id', sa.Uuid(), nullable=False),
    sa.Column('photo_type', sa.Enum('POOL', 'DECK', 'RETURNED', name='phototype'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_player_id'], ['tournament_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('draft_id', 'tournament_player_id', 'photo_type', name='uq_draft_player_photo_type')
    )
    op.create_table('pods',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('draft_id', sa.Uuid(), nullable=False),
    sa.Column('tournament_cube_id', sa.Uuid(), nullable=False),
    sa.Column('pod_number', sa.Integer(), nullable=False),
    sa.Column('pod_size', sa.Integer(), nullable=False),
    sa.Column('timer_ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_cube_id'], ['tournament_cubes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('swiss_round', sa.Integer(), nullable=False),
    sa.Column('player1_id', sa.Uuid(), nullable=False),
    sa.Column('player2_id', sa.Uuid(), nullable=True),
    sa.Column('player1_wins', sa.Integer(), nullable=False),
    sa.Column('player2_wins', sa.Integer(), nullable=False),
    sa.Column('is_bye', sa.Boolean(), nullable=False),
    sa.Column('reported', sa.Boolean(), nullable=False),
    sa.Column('p1_reported_p1_wins', sa.Integer(), nullable=True),
    sa.Column('p1_reported_p2_wins', sa.Integer(), nullable=True),
    sa.Column('p2_reported_p1_wins', sa.Integer(), nullable=True),
    sa.Column('p2_reported_p2_wins', sa.Integer(), nullable=True),
    sa.Column('has_conflict', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player1_id'], ['tournament_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2_id'], ['tournament_players.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pod_players',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('pod_id', sa.Uuid(), nullable=False),
    sa.Column('tournament_player_id', sa.Uuid(), nullable=False),
    sa.Column('seat_number', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pod_id'], ['pods.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tournament_player_id'], ['tournament_players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pod_id', 'tournament_player_id', name='uq_pod_player')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod_players')
    op.drop_table('matches')
    op.drop_table('pods')
    op.drop_table('draft_photos')
    op.drop_table('cube_votes')
    op.drop_table('tournament_players')
    op.drop_table('tournament_cubes')
    op.drop_table('drafts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tournaments_join_code'), table_name='tournaments')
    op.drop_table('tournaments')
    op.drop_table('cubes')
    # ### end Alembic commands ###
